[channels."1 left"]
high = [0x8, "ctrl", 0x0d]
mid = [0x8, "ctrl", 0x31]
low = [0x8, "ctrl", 0x1d]
volume = [0x8, "ctrl", 0x4d]
tog_eq = [0x8, "note", 41]

[channels."1 right"]
high = [0x8, "ctrl", 0x0e]
mid = [0x8, "ctrl", 0x32]
low = [0x8, "ctrl", 0x1e]
volume = [0x8, "ctrl", 0x4e]
tog_eq = [0x8, "note", 42]

[channels."2 left"]
high = [0x8, "ctrl", 0x0f]
mid = [0x8, "ctrl", 0x33]
low = [0x8, "ctrl", 0x1f]
volume = [0x8, "ctrl", 0x4f]
tog_eq = [0x8, "note", 43]

[channels."2 right"]
high = [0x8, "ctrl", 0x10]
mid = [0x8, "ctrl", 0x34]
low = [0x8, "ctrl", 0x20]
volume = [0x8, "ctrl", 0x50]
tog_eq = [0x8, "note", 43]

[channels."3 left"]
high = [0x8, "ctrl", 0x11]
mid = [0x8, "ctrl", 0x35]
low = [0x8, "ctrl", 0x21]
volume = [0x8, "ctrl", 0x51]
tog_eq = [0x8, "note", 43]

[channels."3 right"]
high = [0x8, "ctrl", 0x12]
mid = [0x8, "ctrl", 0x36]
low = [0x8, "ctrl", 0x22]
volume = [0x8, "ctrl", 0x52]
tog_eq = [0x8, "note", 45]

[channels."4 left"]
high = [0x8, "ctrl", 0x13]
mid = [0x8, "ctrl", 0x37]
low = [0x8, "ctrl", 0x23]
volume = [0x8, "ctrl", 0x53]
tog_eq = [0x8, "note", 46]

[channels."4 right"]
high = [0x8, "ctrl", 0x14]
mid = [0x8, "ctrl", 0x38]
low = [0x8, "ctrl", 0x24]
volume = [0x8, "ctrl", 0x54]
tog_eq = [0x8, "note", 60]
